### ISSUE TITLE
Change Video call to VoIP

### ISSUE THREAD

**Issue by joancolmenerodev** [opentok/opentok-ionic-samples#10]
Is possible to change the video-call from your project Basic-Video-Chat to only VoIP?
Only voice, without video?

**Comment by msach22** [comment]
When you initialize the publisher, you can set the`videoSource` property to `false`. This will make it an audio-only call because you will not be able to publish your video. For more information, please look at the docs here: https://github.com/opentok/cordova-plugin-opentok/blob/master/docs/ot.md#initPublisher
